server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: feng-shortlink-admin
          uri: lb://feng-shortlink-admin/api/fenglink/v1/admin/**
          predicates:
            - Path=/api/fenglink/v1/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/fenglink/v1/admin/user/login
                  - /api/fenglink/v1/admin/user/has-username
                  - /api/fenglink/v1/admin/user
        - id: feng-shortlink-project
          uri: lb://feng-shortlink-project/api/fenglink/v1/**
          predicates:
            - Path=/api/fenglink/v1/**
          filters:
            - name: TokenValidate
