spring:
  data:
    redis:
      host: 122.51.165.51
      port: 6379
      password: xWfhdsajklfh@@991
      database: 3
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.165.51:8848
short-link:
  stats:
    locale:
      amap-key: d8ff1fbaa0db78890a8659a25ace740f
  domain: "baidu.com:8001"
  goto-domain:
    white-list:
      enable: false
rocketmq:
  name-server: 122.51.165.51:9876  # tx 地址
  producer:
    group: dev_shortlink-stats-producer-group  # 生产者组